### ISSUE TITLE
Silence SoX's output when playing in linux

### ISSUE THREAD

**Issue by hadware** [DrMarc/slab#24]
When playing a `Sound` object on linux (ubuntu 20.04), I get SoX's typical output. I don't know if that's a wanted behavior,  but flashing from the script to SoX's display was quite confusing from my pov.

I'd advise that you silence SoX by supressing stderr/stdout  at https://github.com/DrMarc/slab/blob/bd41d5fe9514a391b55d7e9e37cee14df670a87d/slab/sound.py#L898 (I don't know which is used by SoX).

**Comment by DrMarc** [comment]
Agree, this is distracting. I've redirected stout and sterr to null.
