### ISSUE TITLE
Nitpicking on examples in the README

### ISSUE THREAD

**Issue by hadware** [DrMarc/slab#25]
Your examples are great, but some things did bug me:

1. The first example has a tab before each of its line, which forced me to "detab" it before being able to run it (i know, i'm lazy, but so is everyone).
2. Examples that show some typical outputs are a bit confusing, you should switch to a fake python prompt or fake ipython prompt style of code examples to represent this, such as 
```python
>>> sig = slab.Sound.pinknoise(nchannels=2) # make a pink noise
>>> sig.duration
1.0
```
(The current `out : 1.0` format kind of feels like a type annotation).

Btw, the example mentioned above has a typo in the `n_channels`  argument :wink:

**Comment by OleBialas** [comment]
I agree that this layout is more intuitive. However if we change it in the readme we should change everything (docstrings, readthedocs) to the same format, @DrMarc what do you think?

**Comment by hadware** [comment]
My advice is that you should only change examples where some output is shown, otherwise it's just fine as it is

**Comment by DrMarc** [comment]
Consistency and convenience are king. We should decide on one format and stick to that throughout the examples. This format should be easy to copy over to an iPython console. The fake iPython style is very common and may be the best option.
@OleBialas - could you check whether it interferes with sphinx? We also need to go over all examples and propagate the recent naming changes (nsamples -> n_samples, nchannels arguments, etc.).

**Comment by hadware** [comment]
> This format should be easy to copy over to an iPython console.

I agree, the `>>> some.code()` format is pretty but throughly annoying when it comes to copying things over to your code/the console.

**Comment by DrMarc** [comment]
Ok. Having your input really helps here; we work mostly with an editor and an ipython console side-by-side, and ipython happily ignores the leading `>>>`. If that's a problem in other environments, then we can go with unindented code and put the output examples in comments. That would be clear and copy nicely.

**Comment by hadware** [comment]
> Having your input really helps here;

Alright, here's a breakdown of what works for mewith the `>>> my.code() ` syntax and what doesn't:
- Python console :red_square: 
- Pycharm console :red_square: 
- Pycharm editor :red_square: 
- Ipython console :heavy_check_mark:  
- Jupyter notebook :heavy_check_mark: 

Hope that helps.
