### ISSUE TITLE
user directory outside repository

### ISSUE THREAD

**Issue by DrMarc** [DrMarc/slab#29]
!>> strongly recommend to create a user directory that is outside the repository or library location, maybe in ~/slab as it makes it more difficult for new programmers to contribute/use the library and makes operation a bit more opaque. (where is my calibration file again?). also becomes a bigger problem when you aren't guaranteed permissions, eg in the case where someone installs it as a system package with `sudo pip install slab`

**Comment by OleBialas** [comment]
I think that is a good idea - can you create a folder in the user directory on Windows/Mac with `~/` ?

**Comment by DrMarc** [comment]
I'm still thinking about this. Points to consider:
- Permissions are a major issue, and the scenario where the module is installed system-wide with sudo, but used with lesser permissions is likely. 
- Putting data in the lib location is indeed suboptimal and opaque. We tried to remedy this somewhat with the slab.data_path() function (i.e. within Python, you rarely need to think about where this files are).
- There are standard locations for application data (and different ones for global and user-specific data), like `~/.local/share`, `~/Library/Application Support`, or `C:/Users/<USER>/AppData/Roaming` in the different OSes, but while these may be correct, they may be equally opaque to the user (hidden in Linux and MacOS). 

The home dir might not be optimal, because it is always user-specific, but the data we put in this folder should ideally apply to all users (they describe the hardware setup (calibration) or universal data (KEMAR)). Perhaps the data_path should be user-settable (that path would still need to be saved somewhere, but that could happen once at install time).

**Comment by DrMarc** [comment]
@OleBialas pathlib.Path.home() would get you the right dir in all OSes.

**Comment by DrMarc** [comment]
After looking it this a bit more, the home dir is strongly discouraged for putting app data. I see two options:
- using something like pypi.org/project/appdirs/ to use the correct directories on each OS (but they aren't any easier to find than the package location)
- changing the architecture to remove the need for this sort of package data.

Looking at other packages and use cases, option 2 appeals to me. The KEMAR HRTF is the only data that we can't generate in the module. I suggest we provide a convenience function to auto-download it to a given directory (also useful for testing). Then it's up to the user to load it and hand it to methods in slab.Binaural that require an HRTF. Some data derived from KEMAR is auto-cached (like the interaural level spectrum), but this is somewhat opaque and it's better practise to let the user generate these data and keep them around in a variable if needed or save them to disk. I think this is more transparent.

This also touches issue #35: We should *not* save state information (like the intensity calibration) anymore. This is currently not consistent (samplerate and level are not saved), and there is considerable potential for unwanted side effects due to the behind-the-curtains treatment of the calibration (am I using it at the moment? Has someone overwritten my default?).
Best practise is how we treat the samplerate: There is a sensible default if you just want to play around a bit, but any serious experimental script would specify the rate etc. at the top.

**Comment by DrMarc** [comment]
I now implemented the approach above. The KEMAR HRTF is still provided (bz2-compressed now) and made available via `slab.HRTF.kemar()`. The user has no access to the data path anymore and now writing rights are needed. This also eliminates hidden states (calibration is not saved and applied automatically and the level spectrum is not cached for KEMAR).
