### ISSUE TITLE
 spectrogram_kwargs

### ISSUE THREAD

**Issue by DrMarc** [DrMarc/slab#32]
!>> wrappers around functions with a lot of parameters should probably take kwargs and give them to the wrapped function. eg. spectrogram passes kwargs to axis.imshow but most of the other params are hard-calculated. would be good to be able to pass in spectrogram_kwargs to override default calculated values if wanted. totally optional QoL thing that would be pretty cheap to implement.

**Comment by OleBialas** [comment]
Ok, so i thought about what would be plotting parameters that one might want to set manually and i think that it's mostly the extent of the axes as well as the titles of the plot. However, one could change those by passing an axes object to plot to and then overwriting the parameters using the axes methods - do you have any other parameters in mind?

**Comment by DrMarc** [comment]
I think the point of the kwargs would be that you can pass any of the options you may need to the underlying scipy spectrogram function. I think the axis options should be set as you describe, which is consistent with Sound.waveform and other plots that can plot into an existing axis.

**Comment by DrMarc** [comment]
fixed as above in latest commit
