### ISSUE TITLE
waveform autoscale optional

### ISSUE THREAD

**Issue by DrMarc** [DrMarc/slab#33]
!>> waveform autoscales the y-axis which makes it a little difficult to compare across amplitudes. maybe make that optional?

**Comment by DrMarc** [comment]
Our intention was that it is very easy to get sensible default plots. For full control, one can pass an axis object to any of the plotting functions and set limits, borders, spacing, etc. as desired:
```
_, axis = plt.subplots()
axis.set_ylim(-1, 1)
sig.waveform(axis=axis)
```
When comparing signals,  you'd probably make several axes in one figure and share dimensions. Passing pre-configured axis objects is more flexible than f.i. adding an argument for the y-axis limits.

**Comment by sneakers-the-rat** [comment]
aha^ would consider adding that to the docs if it wasn't already, but no objections from me since it's not a major point in the library & you have the bigger picture better than me!
