### ISSUE TITLE
consolidate user preferences?

### ISSUE THREAD

**Issue by DrMarc** [DrMarc/slab#35]
!>> calibrations are automatically saved and loaded, which is nice (might be good to give notice that a calibration has been loaded on import) but default samplerates are not. It seems appropriate for this package, since it's intended as a modular tool for users to hack around with/reconfigure/etc., to consolidate user preferences into a single getter/setter method, maybe in a single .pck or .json or .yaml or whatever file so this is easier to maintain.

**Comment by OleBialas** [comment]
I think this is a good idea, but first we have to sort out issue #29 regarding the data directory

**Comment by DrMarc** [comment]
fixed in #64f2b98
We now treat the calibration intensity like _default_samplerate and _default_level. It is not saved and applied behind the curtains, but has to be set explicitly. This is more transparent, avoid issues when several people use a common setup, and makes sense in situation where you want stimulus-type-specific calibration (i.e. calibrating with a noise is more accurate for broadband stimuli).
The following commit will update the docs to reflect this change in strategy.
