### ISSUE TITLE
Testing/Maintaining Binaural class

### ISSUE THREAD

**Issue by sneakers-the-rat** [DrMarc/slab#41]
(optional comment/suggestion)

The Binaural class does what it promises, but as written it seems a little hard to maintain -- sound generation methods from `Sound` have to be overwritten with a call to `Binaural(Sound.method(**kwargs))` . I think you would do yourselves a favor by doing one or two things:

* making an explicit declaration about which methods of the `Sound` class are sound generation methods (looks like they are all `@classmethod`s, so you could make a decorator that wraps `@classmethod` like `@sound` or something that adds to a class-level list?), and then write a test that confirms that for each of the methods in `Sound`, `Binaural` produces the expected behavior

or

* embed some logic in `Binaural` that doubles channels automatically unless the generation method has been overridden... i imagine this could be done by making `self.data` a property with a getter/setter, or else some wrapper around the sound generation methods that does it.

i am just imagining those getting out of sync becoming a headache, hopefully useful, but up to you :)

**Comment by OleBialas** [comment]
I like the idea of a decorator for the sound generating methods better than the "automatic doubling"

**Comment by DrMarc** [comment]
Checking this in the tests is a great idea. We can do that without adding any code to the Sound or Binaural classes by using inspection to get all methods with a 'n_channels' parameter from the Sound class and asserting that they return a 2chan object when called from Binaural, like so:
methods = [attribute for attribute in dir(slab.Sound) if callable(getattr(slab.Sound, attribute)) and attribute.startswith('__') is False]
for method in methods:
    func = getattr(slab.Sound, 'whitenoise')
    args, _, _ = inspect.getargs(func.__code__)
    if 'n_channels' in args:
        # same method in Binaural returns 2-ch object?
        assert(getattr(slab.Binaural, 'whitenoise')().n_channels == 2)

I'll add this test in the next commit.

**Comment by sneakers-the-rat** [comment]
well i am always a sucker for introspection for things that are internally-facing rather than part of an API, and i just want to say i like this solution^
