### ISSUE TITLE
spectrogram window size

### ISSUE THREAD

**Issue by OleBialas** [DrMarc/slab#60]
I think that the code to compute the step size for the spectrogram is missing  a conversion from time to samples:
https://github.com/DrMarc/slab/blob/dd50114884914eca98508bc033cb3963f9c3b36a/slab/sound.py#L1030

**Comment by DrMarc** [comment]
Yes, you are correct. It should be window_n_samples instead of window_dur in this line. Could you correct and send a pull requests?
