### ISSUE TITLE
`test_precomputed()` fails due to missing "tests/config.txt"

### ISSUE THREAD

**Issue by sammosummo** [DrMarc/slab#66]
Hi Marc. I'm planning on submitting a pull request, so I forked the repo and ran the test suite. The test mentioned in the title fails for the stated reason. Seems minor, unsure if you care or not, just thought you might want to add a blank placeholder config file or something.

**Comment by DrMarc** [comment]
Thanks for noticing! The config is not even part of precomputed. I removed the offending line.
