### ISSUE TITLE
Pure tone does not work close to Nyquist frequency

### ISSUE THREAD

**Issue by OleBialas** [DrMarc/slab#71]
I just noticed that it is not possible to create a pure tone at or close to the Nyquist frequency. Here is a plot to show what I mean:

```python
from slab import Sound
from matplotlib import pyplot as plt

sfreq = 8000
freqs = [1000, 2500, 3000, 3500, 4000]
fig, ax = plt.subplots(len(freqs), sharex=True)

for i, freq in enumerate(freqs):
    tone = Sound.tone(frequency=freq, samplerate=sfreq)
    ax[i].plot(tone.times, tone.data, label=f'{freq/1e3} kHz')
    ax[i].legend(loc='upper right', fontsize='small')

ax[0].set_xlim(0, 0.001)
plt.show()
```

![tone_example](https://github.com/DrMarc/slab/assets/38684453/efe2a14b-fc43-4918-aa12-838e56fa0b4d)

This actually affects the [audiogram example](https://slab.readthedocs.io/en/latest/examples.html#audiogram) in the documentation, which includes a 4 kHz tone with the default 8kHz sample rate. I'm not sure what the best way of handling this is. Maybe for now just add a warning for frequencies above 1/3 of the sample rate and increase the sample rate in the audiogram example?

**Comment by DrMarc** [comment]
This is partly due to the difference of just plotting the waveform vs. listening to the resulting tone! Even a strange-looking waveform (when close to the Nyquest freq) will sound fine after going through the reconstruction filter (see https://en.wikipedia.org/wiki/Reconstruction_filter if you have not come across this concept).

**Comment by OleBialas** [comment]
For me, at 8kHz sample rate the 4kHz tone sounds heavily distorted, that is how I stumbled across this in the first place. Does it sound normal to you? If so, it might be an issue with my drivers. Also thanks for the link!
